/**
 * AUTO-GENERATED by scripts/build.mjs from config/providers.json + config/knowledge.json.
 * DO NOT EDIT BY HAND — edit config/*.json (or use the /admin panel) and rebuild.
 */

export const GENERATED_PROVIDERS_CONFIG = {
  "version": 2,
  "_doc": "Admin-panel editable (committed from /admin via the GitHub API). Every change rebuilds Cloudflare Pages automatically. scripts/build.mjs regenerates src/providers/generated-data.js from this file; src/providers/registry.js instantiates every enabled provider from it. API KEYS ARE NEVER STORED HERE — they are Cloudflare env secrets (see /env-setup).",
  "order": [
    "openrouter",
    "opencodezen",
    "poolside",
    "custom"
  ],
  "hidden": [],
  "providers": {
    "openrouter": {
      "id": "openrouter",
      "label": "OpenRouter",
      "description": "Unified gateway to 200+ models (GLM, Llama, DeepSeek, Gemini, Qwen...) with free-tier options.",
      "tagline": "Unified gateway to 200+ models — the free tier (\":free\" models) is auto-listed.",
      "docsUrl": "https://openrouter.ai/docs",
      "baseUrl": "https://openrouter.ai/api/v1",
      "baseUrlEnvKey": null,
      "apiKeyEnv": "OPENROUTER_API_KEY",
      "apiKeyOptional": false,
      "modelEnvKey": "OPENROUTER_MODEL",
      "extraModelEnvKeys": [
        "MODEL_NAME"
      ],
      "defaultModel": "z-ai/glm-5.2:free",
      "freeOnly": true,
      "allowPublicModels": false,
      "openrouterHeaders": true,
      "supportsMaxTokens": true,
      "enabled": true,
      "models": [
        {
          "id": "z-ai/glm-5.2:free",
          "label": "GLM 5.2 (free)",
          "default": true
        },
        {
          "id": "deepseek/deepseek-chat-v3-0324:free",
          "label": "DeepSeek Chat v3 (free)",
          "default": false
        },
        {
          "id": "meta-llama/llama-3.3-70b-instruct:free",
          "label": "Llama 3.3 70B (free)",
          "default": false
        },
        {
          "id": "google/gemma-3-27b-it:free",
          "label": "Gemma 3 27B (free)",
          "default": false
        },
        {
          "id": "qwen/qwen-2.5-72b-instruct:free",
          "label": "Qwen 2.5 72B (free)",
          "default": false
        }
      ]
    },
    "opencodezen": {
      "id": "opencodezen",
      "label": "OpenCode Zen",
      "description": "opencode.ai Zen gateway — coding-tuned frontier models; free tier models like deepseek-v4-flash-free, nemotron-3.5-lightning-free.",
      "tagline": "opencode.ai Zen coding models — only the \"-free\" models are auto-listed.",
      "docsUrl": "https://opencode.ai/docs/zen",
      "baseUrl": "https://opencode.ai/zen/v1",
      "baseUrlEnvKey": null,
      "apiKeyEnv": "OPENCODEZEN_API_KEY",
      "apiKeyOptional": false,
      "modelEnvKey": "OPENCODEZEN_MODEL",
      "extraModelEnvKeys": [],
      "defaultModel": "deepseek-v4-flash-free",
      "freeOnly": true,
      "allowPublicModels": true,
      "openrouterHeaders": false,
      "supportsMaxTokens": true,
      "enabled": true,
      "models": [
        {
          "id": "deepseek-v4-flash-free",
          "label": "DeepSeek v4 Flash (free)",
          "default": true
        },
        {
          "id": "nemotron-3.5-lightning-free",
          "label": "Nemotron 3.5 Lightning (free)",
          "default": false
        },
        {
          "id": "mimo-v2.5-free",
          "label": "MiMo v2.5 (free)",
          "default": false
        },
        {
          "id": "ling-3.0-flash-fin-free",
          "label": "Ling 3.0 Flash Fin (free)",
          "default": false
        }
      ]
    },
    "poolside": {
      "id": "poolside",
      "label": "Poolside AI",
      "description": "Poolside Laguna code-intelligence models for software engineering tasks (code gen, review, refactoring).",
      "tagline": "Poolside Laguna code-intelligence models — full catalog.",
      "docsUrl": "https://poolside.ai",
      "baseUrl": "https://inference.poolside.ai/v1",
      "baseUrlEnvKey": null,
      "apiKeyEnv": "POOLSIDE_API_KEY",
      "apiKeyOptional": false,
      "modelEnvKey": "POOLSIDE_MODEL",
      "extraModelEnvKeys": [],
      "defaultModel": "poolside/laguna-s-2.1",
      "freeOnly": false,
      "allowPublicModels": false,
      "openrouterHeaders": false,
      "supportsMaxTokens": true,
      "enabled": true,
      "models": [
        {
          "id": "poolside/laguna-s-2.1",
          "label": "Laguna S 2.1",
          "default": true
        }
      ]
    },
    "custom": {
      "id": "custom",
      "label": "Custom (OpenAI-compatible)",
      "description": "Any OpenAI-compatible endpoint: OpenAI, DeepSeek, Together, vLLM, Ollama, LM Studio... Configure via CUSTOM_BASE_URL / CUSTOM_API_KEY / CUSTOM_MODEL.",
      "tagline": "Any OpenAI-compatible endpoint — full catalog, zero code.",
      "docsUrl": "/custom-provider/",
      "baseUrl": null,
      "baseUrlEnvKey": "CUSTOM_BASE_URL",
      "apiKeyEnv": "CUSTOM_API_KEY",
      "apiKeyOptional": true,
      "modelEnvKey": "CUSTOM_MODEL",
      "extraModelEnvKeys": [],
      "defaultModel": null,
      "freeOnly": false,
      "allowPublicModels": false,
      "openrouterHeaders": false,
      "supportsMaxTokens": true,
      "enabled": true,
      "models": []
    }
  }
};

export const GENERATED_KNOWLEDGE = {
  "version": 1,
  "_doc": "Chatbot agent knowledge base (editable from /admin → Knowledge tab). Every entry is injected into the chatbot + Telegram bot system prompt so the assistant can answer questions about THIS site with real facts. Markdown allowed in answers.",
  "entries": [
    {
      "topic": "What is this website / API?",
      "tags": [
        "about",
        "what",
        "site",
        "api"
      ],
      "answer": "**AI Gateway API** is a production-ready REST gateway for AI providers. Send **one** `POST /api/v1/chat` request and it routes to OpenRouter, OpenCode Zen, Poolside AI or any OpenAI-compatible provider. If a provider errors, the gateway **automatically fails over** to the next one until a response arrives. Provider API keys live only in server env vars — they are never exposed to browsers."
    },
    {
      "topic": "How to call the chat endpoint (POST)",
      "tags": [
        "chat",
        "post",
        "curl",
        "call",
        "example"
      ],
      "answer": "```bash\ncurl https://aigatewaybd.pages.dev/api/v1/chat \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\"message\": \"Hello!\"}'\n```\nOptional body fields: `provider`, `model`, `system_prompt`, `temperature` (0–2), `max_tokens`, `failover` (false pins one provider). You can also send multi-turn `{\"messages\":[{\"role\":\"user\",\"content\":\"...\"}]}`."
    },
    {
      "topic": "GET shortcut — open the API from a browser link",
      "tags": [
        "get",
        "ask",
        "shortcut",
        "link",
        "browser"
      ],
      "answer": "Two GET-style endpoints work directly in the browser — no headers, no body:\n\n1. `GET /api/v1/chat?prompt=...` — full endpoint.\n2. `GET /ask?prompt=...` — short custom shortcut.\n\nExample: [https://aigatewaybd.pages.dev/ask?prompt=Say%20hi%20in%20Bangla](/ask?prompt=Say%20hi%20in%20Bangla) returns JSON instantly. Add `&raw=1` for plain text, `&provider=poolside` to pin a provider."
    },
    {
      "topic": "Automatic failover",
      "tags": [
        "failover",
        "retry",
        "resilience"
      ],
      "answer": "Failover is ON by default and works at the MODEL level: if a model errors (rate limit, timeout, outage, bad response), the gateway tries EVERY other model of the same provider one by one (up to FAILOVER_MODELS_MAX, default 6, newest-failed models skipped for 5 min); if the whole provider fails, it instantly moves to the NEXT provider and walks all of its models too — cycling up to FAILOVER_MAX_ROUNDS rounds (default 3) with a hard cap of FAILOVER_MAX_ATTEMPTS upstream calls (default 12) until a response arrives. The response reports `provider`, `model` and the full attempt log under `failover`. Set `\"failover\": false` to pin a single provider and its primary model."
    },
    {
      "topic": "Models policy — free only?",
      "tags": [
        "models",
        "free",
        "catalog"
      ],
      "answer": "GET `/api/v1/models` auto-fetches every provider's live catalog. **OpenRouter** and **OpenCode Zen** list only their FREE models (`:free` / `-free` ids); other providers list the full catalog. Results are cached (default 6 h); `?refresh=1` forces a re-fetch. The admin can also pin curated models per provider from the Admin Panel."
    },
    {
      "topic": "How to integrate (JS / Python / Telegram)",
      "tags": [
        "integrate",
        "javascript",
        "python",
        "telegram",
        "guide"
      ],
      "answer": "- **JavaScript/Python/cURL**: copy ready examples from the Guide page (/guide/).\n- **Telegram bot**: full functional webhook + polling code on the Telegram page (/telegram/).\n- **Any app**: call the GET shortcut `/ask?prompt=...` — pure URL integration."
    },
    {
      "topic": "Deployment & environment variables",
      "tags": [
        "deploy",
        "env",
        "cloudflare",
        "setup"
      ],
      "answer": "Deployed on **Cloudflare Pages** from GitHub (build: `npm run build`, output: `out`). All configuration lives in environment variables — the complete importable file with step-by-step instructions is on the **Env Setup** page (/env-setup/)."
    },
    {
      "topic": "Admin panel",
      "tags": [
        "admin",
        "panel",
        "config"
      ],
      "answer": "The owner-only Admin Panel (/admin/) signs in with a GitHub token and provides **full CRUD**: add/edit/delete AI Providers and their models, edit the chatbot knowledge base, site branding, announcement banner and chatbot settings. Every save commits to the GitHub repo → Cloudflare Pages redeploys automatically."
    }
  ]
};
