/**
 * Build script for Cloudflare Pages (Build command: `npm run build`).
 *
 * Cloudflare Pages needs a static "Build output directory" (`out`):
 *   - public/*            -> out/   (docs site, _headers, favicon)
 *   - functions/*         -> bundled automatically by Pages (API endpoints)
 *
 * It also REGENERATES out/assets/js/app-config.js from environment variables
 * so one .env change (APP_VERSION / APP_NAME / API_BASE_URL) rebrands every
 * page after redeploy:
 *
 *   APP_VERSION=1.0.0   -> navbar chip, footer, docs headings, ...
 *   API_BASE_URL=...    -> leave unset to auto-detect from the browser URL
 *
 * This script is intentionally dependency-free and CI-safe: pure Node fs
 * operations, no network, no prompts.
 */
import { rmSync, mkdirSync, cpSync, readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = fileURLToPath(new URL('..', import.meta.url));
const publicDir = join(rootDir, 'public');
const outDir = join(rootDir, 'out');
const configDir = join(rootDir, 'config');

/** Load a JSON file from config/ with a safe fallback. */
function loadConfigJson(fileName, fallback) {
  const file = join(configDir, fileName);
  if (!existsSync(file)) return fallback;
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch (error) {
    console.warn(`[build] WARNING: config/${fileName} is not valid JSON (${error.message}) - using defaults.`);
    return fallback;
  }
}

const DEFAULT_VERSION = '1.4.0';

const DEFAULT_SITE = {
  appName: 'AI Gateway API',
  tagline: 'One AI API. Every provider.',
  description: '',
  announcement: { enabled: false, text: '', link: '', linkLabel: 'Learn more' },
  chatbot: {
    enabled: true,
    name: 'Gateway Assistant',
    welcome: 'Hi! Ask me anything about this API.',
    quickQuestions: [],
    temperature: 0.3,
    maxTokens: 900,
  },
};

const DEFAULT_PROVIDERS_META = { order: [], hidden: [], taglines: {} };

/**
 * CODEGEN: emit src/providers/generated-data.js from config/*.json.
 *
 * The Admin Panel commits config/providers.json + config/knowledge.json to the
 * GitHub repo, Cloudflare Pages re-runs this build, and the BACKEND (Pages
 * Functions + Node server) picks the new data up — that is how full provider /
 * model CRUD from /admin reaches the running API without any code changes.
 */
function generateBackendData(providersConfig, knowledgeConfig) {
  const target = join(rootDir, 'src', 'providers', 'generated-data.js');
  const banner =
    '/**\n' +
    ' * AUTO-GENERATED by scripts/build.mjs from config/providers.json + config/knowledge.json.\n' +
    ' * DO NOT EDIT BY HAND — edit config/*.json (or use the /admin panel) and rebuild.\n' +
    ' */\n\n';
  const body =
    'export const GENERATED_PROVIDERS_CONFIG = ' + JSON.stringify(providersConfig, null, 2) + ';\n\n' +
    'export const GENERATED_KNOWLEDGE = ' + JSON.stringify(knowledgeConfig, null, 2) + ';\n';
  writeFileSync(target, banner + body);
}

function listFilesRecursively(dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const full = join(dir, entry.name);
    return entry.isDirectory() ? listFilesRecursively(full) : [full];
  });
}

try {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  cpSync(publicDir, outDir, { recursive: true });

  // ---- Admin-editable JSON config (single source of truth) -----------------
  const rawProviders = loadConfigJson('providers.json', DEFAULT_PROVIDERS_META);
  const knowledgeConfig = loadConfigJson('knowledge.json', { entries: [] });

  // ---- Regenerate app-config.js from environment variables + config/*.json ----
  const appVersion = String(process.env.APP_VERSION || DEFAULT_VERSION).trim().replace(/^v/i, '') || DEFAULT_VERSION;
  const appNameEnv = String(process.env.APP_NAME || '').trim();
  const apiBase = String(process.env.API_BASE_URL || '').trim().replace(/\/+$/, '');

  // Site + provider DISPLAY config is admin-panel editable: the Admin Panel
  // commits config/site.json + config/providers.json to the GitHub repo,
  // Cloudflare Pages rebuilds automatically, and these values go live.
  const site = { ...DEFAULT_SITE, ...loadConfigJson('site.json', DEFAULT_SITE) };
  site.announcement = { ...DEFAULT_SITE.announcement, ...(site.announcement || {}) };
  site.chatbot = { ...DEFAULT_SITE.chatbot, ...(site.chatbot || {}) };
  const providersMeta = { ...DEFAULT_PROVIDERS_META, ...rawProviders };

  // Backend data module (providers + knowledge) — see generateBackendData().
  generateBackendData(rawProviders, knowledgeConfig);

  // APP_NAME env still wins at runtime (GET /api/v1/config); the JSON value is
  // the build-time default so the site renders correctly even pre-deploy.
  const appName = appNameEnv || String(site.appName || DEFAULT_SITE.appName).trim();

  const appConfigJs = `/**
 * AUTO-GENERATED by scripts/build.mjs — do not edit by hand; set env vars instead.
 * Source of truth: APP_VERSION / APP_NAME / API_BASE_URL (.env or Cloudflare dashboard).
 */
(function () {
  'use strict';
  var AIGW = {
    APP_NAME: ${JSON.stringify(appName)},
    APP_VERSION: ${JSON.stringify(appVersion)},
    API_BASE: ${JSON.stringify(apiBase)},
    apiBase: function () {
      if (this.API_BASE) return String(this.API_BASE).replace(/\\/+$/, '');
      return window.location.origin; // dynamic auto-detection
    },
    fetchServerConfig: function () {
      return fetch(this.apiBase() + '/api/v1/config', { cache: 'no-store' }).then(function (r) {
        if (!r.ok) throw new Error('HTTP ' + r.status);
        return r.json();
      });
    },
    SITE: ${JSON.stringify(site)},
    PROVIDERS_META: ${JSON.stringify(providersMeta)},
    KNOWLEDGE: ${JSON.stringify(knowledgeConfig)},
  };
  window.AIGW = AIGW;
})();
`;
  writeFileSync(join(outDir, 'assets', 'js', 'app-config.js'), appConfigJs);

  // ---- Cache-busting: stamp /assets/* URLs with a build version -------------
  // Without this, browsers keep the OLD css/js for up to 24 h (max-age=86400)
  // after each deploy and visitors see a stale site. Adding ?v=<buildId> makes
  // every deploy a new URL instantly.
  const buildId = `${appVersion}-${Date.now().toString(36)}`;
  let stamped = 0;
  for (const file of listFilesRecursively(outDir)) {
    if (!file.endsWith('.html')) continue;
    let html = readFileSync(file, 'utf8');
    const before = html;
    html = html.replace(/(href="\/assets\/css\/[^"?]+)"/g, `$1?v=${buildId}"`);
    html = html.replace(/(src="\/assets\/js\/[^"?]+)"/g, `$1?v=${buildId}"`);
    if (html !== before) {
      writeFileSync(file, html);
      stamped += 1;
    }
  }

  const files = listFilesRecursively(outDir);
  const sizeBytes = files.reduce((sum, file) => sum + statSync(file).size, 0);

  console.log('[build] AI Gateway API - static assets prepared.');
  console.log(`[build] App config: name="${appName}" version=v${appVersion} apiBase=${apiBase || '(auto-detect)'}`);
  console.log(`[build] Site config: chatbot=${site.chatbot.enabled ? 'on' : 'off'} announcement=${site.announcement.enabled ? 'on' : 'off'} (from config/site.json)`);
  console.log(`[build] Provider data: ${Object.keys(providersMeta.providers || {}).length} provider(s); knowledge entries: ${(knowledgeConfig.entries || []).length} -> src/providers/generated-data.js`);
  console.log(`[build] Copied public/ -> out/ (${files.length} file(s), ${(sizeBytes / 1024).toFixed(1)} KB)`);
  console.log(`[build] Cache-busting: stamped ${stamped} HTML file(s) with v=${buildId}`);
  for (const file of files) {
    console.log(`[build]   - ${relative(outDir, file)}`);
  }
  console.log('[build] API endpoints live under functions/ (bundled by Cloudflare Pages).');
  console.log('[build] Done.');
} catch (error) {
  console.error('[build] FAILED:', error.message);
  process.exit(1);
}
